### ISSUE TITLE
The readme file is a disaster...

### ISSUE THREAD

**Issue by designfrontier** [ansble/safe-shrinkwrap#6]
Needs to be rewritten with better content and links to the license.md, code of conduct and could use a contributor.md file as well.

**Comment by andreybleme** [comment]
@designfrontier Hi. I can help with this one. Can you assign it to me? :+1:

**Comment by designfrontier** [comment]
doesn't seem to want to let me assign it to you... but consider it assigned! 👍

**Comment by willyb321** [comment]
@designfrontier well I've just made a PR. Saw this on [here](https://hacktoberfestchecker.herokuapp.com)

**Comment by designfrontier** [comment]
@andreybleme sorry... if you want to take the changes that @willyb321 is making and add them to the gh-pages site that would also be awesome. I will intentionally not make a ticket for that until right before you are ready so that it doesn't get snagged by someone else.

**Comment by andreybleme** [comment]
@designfrontier the @willyb321 PR seems nice to me :) I would open a PR very similar to this one! :100:

**Comment by willyb321** [comment]
@andreyblame yeah quite sorry about that lol. I had already opened the pr by the time I saw your comment lol!
